[package]
name = "diffie_helmanns"
version = "0.1.0"
authors = ["Victor-Guerra <v.e.g.a.2000@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
